server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: users-service
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:ml}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
  #    data: classpath:/scripts/database/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect